### ISSUE TITLE
OpenSource without License

### ISSUE THREAD

**Issue by FelixWeichselgartner** [rlcmtzc/OpenGBZ#11]
Hi, I saw your repo and it is very interesting.

However, you say it is open source but i cannot find a license (except for some self written words in the readme).

If you would like that others can use the pcbs (without potentially getting sued later), I would recommend using a license (like CC-BY-SA-NC - then you have your non commerical from your text).

Have a nice holiday!

**Comment by rlcmtzc** [comment]
Thanks,
Added the Licensing.
