### ISSUE TITLE
Battery charger problem

### ISSUE THREAD

**Issue by carjufi** [rlcmtzc/OpenGBZ#9]
Hello,

I am using this board for my build and I am having power issues. Basically, the GBZ opens and functions normally with power from the battery, but the circuit does not charge it. 

I have checked the components and my soldering and I cannot find the problem. When I plug the USB-C I see the red LED, so this tells me the TP4056 is working. For the FS312F, I measure the voltage of OD and OC pins to GND and gives me the current voltage of the battery, I assume that if it gives voltage it is working fine. The last IC is the FS8205 and I have tested it as well and works fine, I thought it was a problem of being inverted when I soldered it, so I changed but nothing powered up. Therefore I solder it back again and the GBZ powers on. I assume then it is working fine. 

I really do not understand where is the issue, why it is not charging the battery? Any ideas on how can I check further the components of the circuit?
![Circuit_diagram](https://user-images.githubusercontent.com/38333543/81982944-7ab9a100-962a-11ea-8a98-db81ec7c3466.png)

**Comment by rlcmtzc** [comment]
Are you sure you did not destroied the fs8205 by reversing it? What battery
are you using?

carjufi <notifications@github.com> schrieb am Do., 14. Mai 2020, 22:33:

**Comment by carjufi** [comment]
I did change it as well for a new one just in case. The battery I use is a 4000mAh 3.7V LiPo.

**Comment by rlcmtzc** [comment]
Ok thats good. Have you meassured the volatge and the currend coming from
the battery port without conecting a battery?

carjufi <notifications@github.com> schrieb am So., 17. Mai 2020, 23:39:

**Comment by carjufi** [comment]
No, do you mean checking the voltage from GND in the USB-C to BAT+ without battery? I guess I need to check this with the switch on and the USB-C connected, right?
Where do I have to put the multimeters testers to check for the amperage you mention? 

Sorry I normally do voltage and continuity checks with the multimeter but never tested the amperage before. As you can see I am no expert in this haha, sorry.

**Comment by rlcmtzc** [comment]
No the voltage between the bat+ to bat- wit some kind of loar like a
resistor and the amperege you meassure in series of the bat- connection or
b@t+ connection

carjufi <notifications@github.com> schrieb am Mo., 18. Mai 2020, 17:04:
